version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=MISPCHANGEME
      - MARIADB_USER=misp
      - MARIADB_PASSWORD=mispchangeme
      - MARIADB_DATABASE=misp
      - MARIADB_EXTRA_FLAGS=--max_connections=500
    sysctls:
      net.core.somaxconn: 65535
  redis:
    image: 'bitnami/redis:4.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  misp:
    image: 'misp:latest'
    environment: 
      - MARIADB_HOSTNAME=mariadb_1
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=misp
      - MARIADB_USER=misp
      - MARIADB_PASSWORD=mispchangeme
      - REDIS_HOSTNAME=mariadb_1
      - REDIS_PORT=6379
    ports:
      - '8443:443'

volumes:
  mariadb_data:
    driver: local
